name: Laravel CI

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, exif, pcntl, bcmath, gd, zip

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} -p ${{ secrets.SERVER_PASSWORD }} "cd ${{ secrets.SERVER_PATH }} && git pull origin production && ${{ secrets.DEPLOY_COMMAND }}"
